name: Publish Hero-Style to s3
on:
  push:
    branches:
      - master

jobs:
  build:
    name:  Publish Hero-Style to s3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: CI=false npm run build-storybook --if-present

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude "index.html" --follow-symlinks --metadata "Accept-Encoding=gzip" --cache-control "max-age=14400" --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE_DIR: './storybook-static'      # optional: defaults to entire repository
      - name: Deploy index.html as static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exclude '*' --include "index.html" --acl public-read --follow-symlinks --metadata "Accept-Encoding=gzip" --cache-control "max-age=0,public,proxy-revalidate,must-revalidate" --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE_DIR: './storybook-static'      # optional: defaults to entire repository
